### ISSUE TITLE
Looking for someone to change my params.

### ISSUE THREAD

**Issue by mzaboss** [msaville8/snapchat#1]
Hello,

I just hooked an jailbroken device, and I extracted the Tokens.

However, I managed to use addfriend endpoint. and works perfectly.

But I tried to send a snap with failed attempt. sounds my image doesn't upload to snapchat servers for some reasons.

I need somebody to fix the params. Its a NodeJS script.

code: https://gist.github.com/mzaboss/9d4be77151eb7f366d6d69f0aacbb479

If you can help me am willing to pay good. Skype: mzaboss

Thank you,
regards.

**Comment by LegitSoulja** [comment]
@mzaboss Do you still need help?

**Comment by mzaboss** [comment]
I no longer interested in Snapchat. its a waste of time. I am more into Instagram nowadays. if you are into Instagram unofficial API. please add me in skype: mzaboss

**Comment by LegitSoulja** [comment]
@mzaboss I'm good. I don't use social media as often. I don't really too much care about it. Only snapchat is what I use.

**Comment by LegitSoulja** [comment]
You should close this issue.
